// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkylWrAgqDoWfDCapw--SPjO8ghj37bY',
    appId: '1:17868261879:web:ad52a3c72ffe89d7c086f2',
    messagingSenderId: '17868261879',
    projectId: 'medconnect-1041d',
    authDomain: 'medconnect-1041d.firebaseapp.com',
    storageBucket: 'medconnect-1041d.firebasestorage.app',
    measurementId: 'G-0F78X5SDMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHxeFUW9d-vWIldpeFXgyM1PgXVs_3rc',
    appId: '1:17868261879:android:ae58c36418d6af3bc086f2',
    messagingSenderId: '17868261879',
    projectId: 'medconnect-1041d',
    storageBucket: 'medconnect-1041d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskkwJtV8FDABd8L-qY6givvkJrEVLbnc',
    appId: '1:17868261879:ios:efbd0488ebaeb248c086f2',
    messagingSenderId: '17868261879',
    projectId: 'medconnect-1041d',
    storageBucket: 'medconnect-1041d.firebasestorage.app',
    iosBundleId: 'com.example.mediconnect',
  );
}
